services:
  app:
    build: .
    image: urbunix/flows-ia:latest
    env_file: .env
    volumes:
      - ./outputs:/app/outputs
      - ./data:/app/data
      - ./config:/app/config
    working_dir: /app
    command: ["python", "-m", "cli", "--help"]
    restart: "no"
    healthcheck:
      test: ["CMD", "python", "-c", "import geopandas,shapely; print('ok')"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s

  api:
    build: .
    image: urbunix/flows-ia:latest
    env_file: .env
    volumes:
      - ./outputs:/app/outputs
      - ./data:/app/data
      - ./config:/app/config
    working_dir: /app
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - app
    restart: unless-stopped