services:
  app:
    tty: true
    stdin_open: true
    build: .
    env_file: [.env]
    working_dir: /app
    volumes:
      - ./out:/app/out
      - ./config:/app/config
    command: ["python","-m","cli","--help"]
