name: flows
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # Geospatial
  - gdal
  - geopandas
  - shapely>=2.0
  - pyproj
  - fiona
  - rtree
  - libspatialindex
  - h3-py
  # Data science
  - pandas
  - numpy
  - networkx
  # Scraping / parsing
  - httpx
  - beautifulsoup4
  - lxml
  - pdfplumber
  - pyyaml
  - pydantic>=2
  - tqdm
  - orjson
  - fastapi
  - uvicorn
  # OCR / PDF tooling
  - tesseract
  - pytesseract
  - poppler
  - ghostscript
  # Dev
  - black
  - isort
  - pip:
      - typer[all]
