municipio: "<<<Cidade>>>"
uf: "<<<UF>>>"
ibge_cod_municipio: "<<<IBGE7>>>"
arcgis_zoneamento_layer: "<<<URL layer zoneamento (ArcGIS REST)>>>"
siglon_divisao_territorial_shp: "<<<URL SHP divisao territorial/bairros>>>"
saude_portal_raizes:
  - "<<<URL raiz saude (UBS/UPA)>>>"
educacao_pdf_lista: "<<<URL lista escolas/CMEIs>>>"
assistencia_pages:
  cras: "<<<URL oficial CRAS>>>"
  creas: "<<<URL oficial CREAS>>>"
  centro_pop: "<<<URL oficial Centro POP>>>"
transporte_portal:
  horarios: "<<<URL horarios de onibus>>>"
  gtfs: "<<<URL GTFS se existir>>>"
lei_sistema_viario_pdf: "<<<URL lei sistema viario>>>"
